[project]
name = "familiar-tree"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faker>=37.6.0",
    "peewee>=3.18.2",
    "pydantic>=2.11.7",
]
